### ISSUE TITLE
Parser output requirements 

### ISSUE THREAD

**Issue by dmlemeshko** [elastic/apm-parser#2]
This is a meta issue to track down all the requirements for the data coming as output from apm-parser:

- file format: json
- content:
  -  each file contains traces of http requests to Kibana server including timestamp, request method, headers, body (if applicable), url path and transaction id as a minimum
  - new file for each single-user benchmarking journey
  - traces should contain all the requests executed during journey, from browser open to when it is closed.
  - no duplicated transactions/traces
-  structure:
```
{
    "journeyName": "Sample data dashboard journey",
    "kibanaVersion": "v7.17.1",
    "kibanaUrl": "http://localhost:5260",
    "maxUsersCount": 200,
    "traceItems": []
}
```

@suchcodemuchwow @mshustov @danielmitterdorfer

**Comment by danielmitterdorfer** [comment]
> traces of http requests to Kibana server

As we want to leverage the APM data for multiple purposes (e.g. also to generate query traces from Kibana server -> Elasticsearch server) it would be best if all information is contain in one output file and we include a property that describes the originator of a request, e.g. `kibana-frontend`, `kibana-server`. For scalability benchmarks we would only include requests that originate from `kibana-frontend`. Wdyt?


> timestamp

Can we specify the timestamp format more precisely? I suggest that we use a monotonically increasing number that starts at zero for the first request in the output file. Its data type is a `double` number denoting elapsed seconds from the first request with whatever precision is available from the source system (I'd assume it's either milli- or microseconds). Example value: `1.244` (seconds).

> kibanaVersion

In addition we should also include the SHA. This can be useful for traces that have been created against `main`.

**Comment by dmlemeshko** [comment]
Closed in favour of #elastic/kibana/issues/135049
